version: "3.7"

services:
  map-compare-ui:
    build: .
    image: map-compare-ui:latest
    ports: 
      - "8081:8081"
    container_name: "map-compare-ui"
    networks: 
      - mapui

networks: 
  mapui:
    name: map-compare-ui
    driver: bridge
